name: bloggerton
favicon: null
layout_spectrum: 0.99358
typography_spectrum: 0.99541
title: 'Greg Bolton, JAM3 CD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9b197'
    - '#00d1fb'
    - '#272302'
    - '#c8009b'
  brandStrength: 0.8125
  lightness: 0.020547161111608148
  saturation: 0.8493812324013561
  rhythmicContrast: 0.4975579809397459
purpose: []
