typography_spectrum: 0.93814
color:
  brandColors:
    - '#ffffff'
    - '#e9b197'
    - '#00d1fb'
    - '#272302'
    - '#c8009b'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70932
analytics:
  google: null
  facebook: null
  twitter: null
name: bloggerton
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Greg Bolton
description: 'Creative Director, Jam3.com'
purpose: []
