name: bloggerton
favicon: null
layout_spectrum: 0.17189686256460845
typography_spectrum: 0.022491598036140203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8949109637178481
  lightness: 0.020547161111608148
  saturation: 0.8493812324013561
  rhythmicContrast: 0.4975579809397459
purpose: []
